Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ubuntu/miniconda3/envs/jupybook/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rd


# filename = "https://github.com/pcsi3physiquestan/donnees_exp/blob/main/lambert.dat?raw=true"  # Lien vers le fichier de donn√©es
filename = "../../../../../approche_numeriques/donnees_exp/lambert.dat"  # Lien vers le fichier de donn√©es
A, C, uC = np.loadtxt(filename, skiprows=1, delimiter=",", unpack=True)  # Importation des donn√©es
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-1-a8ada5890861>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;31m# filename = "https://github.com/pcsi3physiquestan/donnees_exp/blob/main/lambert.dat?raw=true"  # Lien vers le fichier de donn√©es[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mfilename[0m [0;34m=[0m [0;34m"../../../../../approche_numeriques/donnees_exp/lambert.dat"[0m  [0;31m# Lien vers le fichier de donn√©es[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mA[0m[0;34m,[0m [0mC[0m[0;34m,[0m [0muC[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mloadtxt[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mskiprows[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mdelimiter[0m[0;34m=[0m[0;34m","[0m[0;34m,[0m [0munpack[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m  [0;31m# Importation des donn√©es[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/miniconda3/envs/jupybook/lib/python3.9/site-packages/numpy/lib/npyio.py[0m in [0;36mloadtxt[0;34m(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)[0m
[1;32m    959[0m             [0mfname[0m [0;34m=[0m [0mos_fspath[0m[0;34m([0m[0mfname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    960[0m         [0;32mif[0m [0m_is_string_like[0m[0;34m([0m[0mfname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 961[0;31m             [0mfh[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlib[0m[0;34m.[0m[0m_datasource[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m'rt'[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    962[0m             [0mfencoding[0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0mfh[0m[0;34m,[0m [0;34m'encoding'[0m[0;34m,[0m [0;34m'latin1'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    963[0m             [0mfh[0m [0;34m=[0m [0miter[0m[0;34m([0m[0mfh[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/jupybook/lib/python3.9/site-packages/numpy/lib/_datasource.py[0m in [0;36mopen[0;34m(path, mode, destpath, encoding, newline)[0m
[1;32m    193[0m [0;34m[0m[0m
[1;32m    194[0m     [0mds[0m [0;34m=[0m [0mDataSource[0m[0;34m([0m[0mdestpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 195[0;31m     [0;32mreturn[0m [0mds[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m,[0m [0mnewline[0m[0;34m=[0m[0mnewline[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    196[0m [0;34m[0m[0m
[1;32m    197[0m [0;34m[0m[0m

[0;32m~/miniconda3/envs/jupybook/lib/python3.9/site-packages/numpy/lib/_datasource.py[0m in [0;36mopen[0;34m(self, path, mode, encoding, newline)[0m
[1;32m    533[0m                                       encoding=encoding, newline=newline)
[1;32m    534[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 535[0;31m             [0;32mraise[0m [0mIOError[0m[0;34m([0m[0;34m"%s not found."[0m [0;34m%[0m [0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    536[0m [0;34m[0m[0m
[1;32m    537[0m [0;34m[0m[0m

[0;31mOSError[0m: ../../../../../approche_numeriques/donnees_exp/lambert.dat not found.
OSError: ../../../../../approche_numeriques/donnees_exp/lambert.dat not found.

